_home:
    pattern:  /
    defaults: { _controller: ChecklistiChecklistBundle:Static:index, page: index }
    requirements:
        _method:  GET

_static:
    pattern:  /static/{page}
    defaults: { _controller: ChecklistiChecklistBundle:Static:index, page: index }
    requirements:
        _method:  GET

_checklist:
    pattern:  /checklist
    defaults: { _controller: ChecklistiChecklistBundle:Checklist:index}

_checklist_new:
    pattern:  /checklist/new
    defaults: { _controller: ChecklistiChecklistBundle:Checklist:edit, id: null}

_checklist_edit:
    pattern:  /checklist/edit/{id}
    defaults: { _controller: ChecklistiChecklistBundle:Checklist:edit}