parameters:
#    checklisti_checklist.example.class: Checklisti\ChecklistBundle\Example

services:
#    checklisti_checklist.example:
#        class: %checklisti_checklist.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
